const { initializeApp } = require("firebase/app");
const {
  getFirestore,
  collection,
  doc,
  setDoc,
  getDocs,
  query,
  where,
} = require("firebase/firestore");

// Firebase config (same as Firebaseconfig.ts)
const firebaseConfig = {
  apiKey: "AIzaSyAVb0lcokEaDJ3oq53VasYUg2IX4A_oBDA",
  authDomain: "nova-b980c.firebaseapp.com",
  projectId: "nova-b980c",
  storageBucket: "nova-b980c.firebasestorage.app",
  messagingSenderId: "220110823698",
  appId: "1:220110823698:web:776c0c5c00c7d9109f13cb",
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

// Categories data
const categories = [
  {
    id: "electronics",
    name: "Electronics",
    icon: "📱",
    color: "#3b82f6",
    subcategories: ["Phones", "Laptops", "Tablets", "Accessories", "Wearables"],
  },
  {
    id: "fashion",
    name: "Fashion",
    icon: "👕",
    color: "#ec4899",
    subcategories: ["Men", "Women", "Kids", "Shoes", "Accessories"],
  },
  {
    id: "home",
    name: "Home",
    icon: "🏠",
    color: "#10b981",
    subcategories: ["Furniture", "Decor", "Kitchen", "Bedding", "Lighting"],
  },
  {
    id: "beauty",
    name: "Beauty",
    icon: "💄",
    color: "#f59e0b",
    subcategories: ["Skincare", "Makeup", "Haircare", "Fragrance", "Tools"],
  },
  {
    id: "sports",
    name: "Sports",
    icon: "⚽",
    color: "#ef4444",
    subcategories: [
      "Equipment",
      "Clothing",
      "Shoes",
      "Supplements",
      "Accessories",
    ],
  },
  {
    id: "books",
    name: "Books",
    icon: "📚",
    color: "#8b5cf6",
    subcategories: ["Fiction", "Non-Fiction", "Academic", "Children", "Comics"],
  },
];

// Products data (12+ per category, 72 total)
const products = [
  // Electronics (12 products)
  {
    id: "e1",
    name: "iPhone 15 Pro",
    price: 999,
    category: "Electronics",
    rating: 4.8,
    image: "https://picsum.photos/200/200?random=1",
    inStock: true,
    stock: 50,
    trending: true,
    discount: 10,
    originalPrice: 1099,
    description: "Latest iPhone with A17 Pro chip",
  },
  {
    id: "e2",
    name: "MacBook Air M3",
    price: 1299,
    category: "Electronics",
    rating: 4.9,
    image: "https://picsum.photos/200/200?random=2",
    inStock: true,
    stock: 30,
    trending: true,
    description: "Lightweight laptop with M3 chip",
  },
  {
    id: "e3",
    name: "Samsung Galaxy S24",
    price: 899,
    category: "Electronics",
    rating: 4.7,
    image: "https://picsum.photos/200/200?random=3",
    inStock: true,
    stock: 45,
    trending: false,
    discount: 15,
    originalPrice: 999,
  },
  {
    id: "e4",
    name: "iPad Pro 12.9",
    price: 1099,
    category: "Electronics",
    rating: 4.8,
    image: "https://picsum.photos/200/200?random=4",
    inStock: true,
    stock: 25,
    trending: true,
    description: "Professional tablet with M2 chip",
  },
  {
    id: "e5",
    name: "Sony WH-1000XM5",
    price: 349,
    category: "Electronics",
    rating: 4.9,
    image: "https://picsum.photos/200/200?random=5",
    inStock: true,
    stock: 60,
    trending: true,
    description: "Noise-cancelling headphones",
  },
  {
    id: "e6",
    name: "Apple Watch Ultra 2",
    price: 799,
    category: "Electronics",
    rating: 4.7,
    image: "https://picsum.photos/200/200?random=6",
    inStock: true,
    stock: 40,
    trending: false,
    description: "Rugged smartwatch for athletes",
  },
  {
    id: "e7",
    name: "Dell XPS 15",
    price: 1499,
    category: "Electronics",
    rating: 4.6,
    image: "https://picsum.photos/200/200?random=7",
    inStock: true,
    stock: 20,
    trending: false,
    discount: 20,
    originalPrice: 1699,
  },
  {
    id: "e8",
    name: "AirPods Pro 2",
    price: 249,
    category: "Electronics",
    rating: 4.8,
    image: "https://picsum.photos/200/200?random=8",
    inStock: true,
    stock: 100,
    trending: true,
    description: "Wireless earbuds with ANC",
  },
  {
    id: "e9",
    name: 'LG OLED TV 65"',
    price: 1999,
    category: "Electronics",
    rating: 4.8,
    image: "https://picsum.photos/200/200?random=9",
    inStock: true,
    stock: 15,
    trending: false,
    description: "4K OLED smart TV",
  },
  {
    id: "e10",
    name: "Nintendo Switch OLED",
    price: 349,
    category: "Electronics",
    rating: 4.7,
    image: "https://picsum.photos/200/200?random=10",
    inStock: true,
    stock: 35,
    trending: false,
    discount: 5,
    originalPrice: 369,
  },
  {
    id: "e11",
    name: "Google Pixel 8 Pro",
    price: 899,
    category: "Electronics",
    rating: 4.6,
    image: "https://picsum.photos/200/200?random=11",
    inStock: true,
    stock: 28,
    trending: false,
    description: "AI-powered smartphone",
  },
  {
    id: "e12",
    name: "Bose QC Ultra Earbuds",
    price: 299,
    category: "Electronics",
    rating: 4.7,
    image: "https://picsum.photos/200/200?random=12",
    inStock: true,
    stock: 50,
    trending: false,
    description: "Premium wireless earbuds",
  },

  // Fashion (12 products)
  {
    id: "f1",
    name: "Levi's 501 Jeans",
    price: 69,
    category: "Fashion",
    rating: 4.5,
    image: "https://picsum.photos/200/200?random=13",
    inStock: true,
    stock: 200,
    trending: false,
    description: "Classic straight fit jeans",
  },
  {
    id: "f2",
    name: "Nike Air Max 270",
    price: 150,
    category: "Fashion",
    rating: 4.8,
    image: "https://picsum.photos/200/200?random=14",
    inStock: true,
    stock: 150,
    trending: true,
    description: "Comfortable running shoes",
  },
  {
    id: "f3",
    name: "Ralph Lauren Polo",
    price: 89,
    category: "Fashion",
    rating: 4.6,
    image: "https://picsum.photos/200/200?random=15",
    inStock: true,
    stock: 100,
    trending: false,
    discount: 10,
    originalPrice: 99,
  },
  {
    id: "f4",
    name: "Adidas Ultraboost",
    price: 180,
    category: "Fashion",
    rating: 4.7,
    image: "https://picsum.photos/200/200?random=16",
    inStock: true,
    stock: 80,
    trending: true,
    description: "High-performance running shoes",
  },
  {
    id: "f5",
    name: "Zara Wool Coat",
    price: 199,
    category: "Fashion",
    rating: 4.5,
    image: "https://picsum.photos/200/200?random=17",
    inStock: true,
    stock: 60,
    trending: false,
    description: "Winter wool blend coat",
  },
  {
    id: "f6",
    name: "Gucci Sneakers",
    price: 690,
    category: "Fashion",
    rating: 4.9,
    image: "https://picsum.photos/200/200?random=18",
    inStock: true,
    stock: 30,
    trending: true,
    description: "Luxury branded sneakers",
  },
  {
    id: "f7",
    name: "H&M Cotton T-Shirt",
    price: 15,
    category: "Fashion",
    rating: 4.2,
    image: "https://picsum.photos/200/200?random=19",
    inStock: true,
    stock: 300,
    trending: false,
    description: "Basic cotton t-shirt pack",
  },
  {
    id: "f8",
    name: "Puma Track Pants",
    price: 55,
    category: "Fashion",
    rating: 4.4,
    image: "https://picsum.photos/200/200?random=20",
    inStock: true,
    stock: 120,
    trending: false,
    discount: 15,
    originalPrice: 65,
  },
  {
    id: "f9",
    name: "North Face Jacket",
    price: 199,
    category: "Fashion",
    rating: 4.8,
    image: "https://picsum.photos/200/200?random=21",
    inStock: true,
    stock: 70,
    trending: true,
    description: "Waterproof outdoor jacket",
  },
  {
    id: "f10",
    name: "Ray-Ban Aviators",
    price: 153,
    category: "Fashion",
    rating: 4.7,
    image: "https://picsum.photos/200/200?random=22",
    inStock: true,
    stock: 90,
    trending: false,
    description: "Classic sunglasses",
  },
  {
    id: "f11",
    name: "Converse All Star",
    price: 60,
    category: "Fashion",
    rating: 4.5,
    image: "https://picsum.photos/200/200?random=23",
    inStock: true,
    stock: 180,
    trending: false,
    description: "Iconic canvas sneakers",
  },
  {
    id: "f12",
    name: "Calvin Klein Dress",
    price: 129,
    category: "Fashion",
    rating: 4.6,
    image: "https://picsum.photos/200/200?random=24",
    inStock: true,
    stock: 55,
    trending: false,
    discount: 20,
    originalPrice: 149,
  },

  // Home (12 products)
  {
    id: "h1",
    name: "Dyson V15 Vacuum",
    price: 749,
    category: "Home",
    rating: 4.9,
    image: "https://picsum.photos/200/200?random=25",
    inStock: true,
    stock: 40,
    trending: true,
    description: "Cordless vacuum cleaner",
  },
  {
    id: "h2",
    name: "IKEA KALLAX Shelf",
    price: 89,
    category: "Home",
    rating: 4.5,
    image: "https://picsum.photos/200/200?random=26",
    inStock: true,
    stock: 100,
    trending: false,
    description: "Storage shelf unit",
  },
  {
    id: "h3",
    name: "Nespresso Machine",
    price: 199,
    category: "Home",
    rating: 4.7,
    image: "https://picsum.photos/200/200?random=27",
    inStock: true,
    stock: 60,
    trending: true,
    description: "Coffee capsule machine",
  },
  {
    id: "h4",
    name: "Philips Air Fryer",
    price: 159,
    category: "Home",
    rating: 4.8,
    image: "https://picsum.photos/200/200?random=28",
    inStock: true,
    stock: 80,
    trending: true,
    description: "Healthy air frying",
  },
  {
    id: "h5",
    name: "Tempur-Pedic Pillow",
    price: 129,
    category: "Home",
    rating: 4.6,
    image: "https://picsum.photos/200/200?random=29",
    inStock: true,
    stock: 120,
    trending: false,
    discount: 10,
    originalPrice: 139,
  },
  {
    id: "h6",
    name: "KitchenAid Mixer",
    price: 379,
    category: "Home",
    rating: 4.9,
    image: "https://picsum.photos/200/200?random=30",
    inStock: true,
    stock: 35,
    trending: false,
    description: "Stand mixer for baking",
  },
  {
    id: "h7",
    name: "Philips Hue Lights",
    price: 199,
    category: "Home",
    rating: 4.5,
    image: "https://picsum.photos/200/200?random=31",
    inStock: true,
    stock: 70,
    trending: false,
    description: "Smart LED lighting",
  },
  {
    id: "h8",
    name: "IKEA Poäng Chair",
    price: 129,
    category: "Home",
    rating: 4.4,
    image: "https://picsum.photos/200/200?random=32",
    inStock: true,
    stock: 50,
    trending: false,
    discount: 15,
    originalPrice: 149,
  },
  {
    id: "h9",
    name: "Dyson Purifier Cool",
    price: 549,
    category: "Home",
    rating: 4.8,
    image: "https://picsum.photos/200/200?random=33",
    inStock: true,
    stock: 25,
    trending: true,
    description: "Air purifier and fan",
  },
  {
    id: "h10",
    name: "Cuisinart Cookware",
    price: 299,
    category: "Home",
    rating: 4.7,
    image: "https://picsum.photos/200/200?random=34",
    inStock: true,
    stock: 45,
    trending: false,
    description: "10-piece cookware set",
  },
  {
    id: "h11",
    name: "Bamboo Bed Sheets",
    price: 89,
    category: "Home",
    rating: 4.6,
    image: "https://picsum.photos/200/200?random=35",
    inStock: true,
    stock: 150,
    trending: false,
    description: "Eco-friendly bed sheets",
  },
  {
    id: "h12",
    name: "Ring Video Doorbell",
    price: 99,
    category: "Home",
    rating: 4.5,
    image: "https://picsum.photos/200/200?random=36",
    inStock: true,
    stock: 90,
    trending: false,
    discount: 20,
    originalPrice: 119,
  },

  // Beauty (12 products)
  {
    id: "b1",
    name: "Estée Lauder Serum",
    price: 98,
    category: "Beauty",
    rating: 4.7,
    image: "https://picsum.photos/200/200?random=37",
    inStock: true,
    stock: 80,
    trending: true,
    description: "Advanced night repair serum",
  },
  {
    id: "b2",
    name: "Dyson Airwrap",
    price: 599,
    category: "Beauty",
    rating: 4.9,
    image: "https://picsum.photos/200/200?random=38",
    inStock: true,
    stock: 30,
    trending: true,
    description: "Multi-styler for hair",
  },
  {
    id: "b3",
    name: "Fenty Beauty Foundation",
    price: 36,
    category: "Beauty",
    rating: 4.6,
    image: "https://picsum.photos/200/200?random=39",
    inStock: true,
    stock: 120,
    trending: false,
    description: "Pro filt'r foundation",
  },
  {
    id: "b4",
    name: "Charlotte Tilbury Lipstick",
    price: 34,
    category: "Beauty",
    rating: 4.8,
    image: "https://picsum.photos/200/200?random=40",
    inStock: true,
    stock: 100,
    trending: false,
    discount: 10,
    originalPrice: 38,
  },
  {
    id: "b5",
    name: "The Ordinary Niacinamide",
    price: 12,
    category: "Beauty",
    rating: 4.5,
    image: "https://picsum.photos/200/200?random=41",
    inStock: true,
    stock: 200,
    trending: false,
    description: "Skin brightening serum",
  },
  {
    id: "b6",
    name: "Olaplex Hair Perfector",
    price: 28,
    category: "Beauty",
    rating: 4.7,
    image: "https://picsum.photos/200/200?random=42",
    inStock: true,
    stock: 150,
    trending: true,
    description: "Bond building treatment",
  },
  {
    id: "b7",
    name: "Urban Decay Palette",
    price: 54,
    category: "Beauty",
    rating: 4.6,
    image: "https://picsum.photos/200/200?random=43",
    inStock: true,
    stock: 90,
    trending: false,
    description: "Naked eyeshadow palette",
  },
  {
    id: "b8",
    name: "CeraVe Moisturizer",
    price: 19,
    category: "Beauty",
    rating: 4.8,
    image: "https://picsum.photos/200/200?random=44",
    inStock: true,
    stock: 250,
    trending: false,
    discount: 5,
    originalPrice: 20,
  },
  {
    id: "b9",
    name: "Dior Sauvage",
    price: 125,
    category: "Beauty",
    rating: 4.9,
    image: "https://picsum.photos/200/200?random=45",
    inStock: true,
    stock: 60,
    trending: true,
    description: "Men's fragrance",
  },
  {
    id: "b10",
    name: "Foreo Luna 4",
    price: 199,
    category: "Beauty",
    rating: 4.5,
    image: "https://picsum.photos/200/200?random=46",
    inStock: true,
    stock: 40,
    trending: false,
    description: "Facial cleansing device",
  },
  {
    id: "b11",
    name: "Benefit Brow Pencil",
    price: 24,
    category: "Beauty",
    rating: 4.4,
    image: "https://picsum.photos/200/200?random=47",
    inStock: true,
    stock: 130,
    trending: false,
    description: "Precise brow pencil",
  },
  {
    id: "b12",
    name: "La Mer Cream",
    price: 345,
    category: "Beauty",
    rating: 4.8,
    image: "https://picsum.photos/200/200?random=48",
    inStock: true,
    stock: 25,
    trending: false,
    discount: 15,
    originalPrice: 395,
  },

  // Sports (12 products)
  {
    id: "s1",
    name: "Bowflex Dumbbells",
    price: 429,
    category: "Sports",
    rating: 4.7,
    image: "https://picsum.photos/200/200?random=49",
    inStock: true,
    stock: 35,
    trending: true,
    description: "Adjustable dumbbells",
  },
  {
    id: "s2",
    name: "Fitbit Versa 4",
    price: 229,
    category: "Sports",
    rating: 4.5,
    image: "https://picsum.photos/200/200?random=50",
    inStock: true,
    stock: 70,
    trending: false,
    description: "Health and fitness watch",
  },
  {
    id: "s3",
    name: "Yoga Mat Premium",
    price: 49,
    category: "Sports",
    rating: 4.6,
    image: "https://picsum.photos/200/200?random=51",
    inStock: true,
    stock: 150,
    trending: false,
    discount: 10,
    originalPrice: 55,
  },
  {
    id: "s4",
    name: "Peloton Bike+",
    price: 2495,
    category: "Sports",
    rating: 4.9,
    image: "https://picsum.photos/200/200?random=52",
    inStock: true,
    stock: 20,
    trending: true,
    description: "Connected exercise bike",
  },
  {
    id: "s5",
    name: "Nike Pro Shorts",
    price: 35,
    category: "Sports",
    rating: 4.4,
    image: "https://picsum.photos/200/200?random=53",
    inStock: true,
    stock: 200,
    trending: false,
    description: "Athletic shorts",
  },
  {
    id: "s6",
    name: "Garmin Fenix 7",
    price: 699,
    category: "Sports",
    rating: 4.8,
    image: "https://picsum.photos/200/200?random=54",
    inStock: true,
    stock: 40,
    trending: false,
    description: "GPS multisport watch",
  },
  {
    id: "s7",
    name: "TriggerPoint Foam Roller",
    price: 39,
    category: "Sports",
    rating: 4.5,
    image: "https://picsum.photos/200/200?random=55",
    inStock: true,
    stock: 100,
    trending: false,
    discount: 15,
    originalPrice: 46,
  },
  {
    id: "s8",
    name: "Adidas Soccer Ball",
    price: 45,
    category: "Sports",
    rating: 4.6,
    image: "https://picsum.photos/200/200?random=56",
    inStock: true,
    stock: 120,
    trending: false,
    description: "FIFA approved ball",
  },
  {
    id: "s9",
    name: "Hydro Flask 32oz",
    price: 44,
    category: "Sports",
    rating: 4.9,
    image: "https://picsum.photos/200/200?random=57",
    inStock: true,
    stock: 180,
    trending: true,
    description: "Insulated water bottle",
  },
  {
    id: "s10",
    name: "Resistance Bands Set",
    price: 29,
    category: "Sports",
    rating: 4.3,
    image: "https://picsum.photos/200/200?random=58",
    inStock: true,
    stock: 250,
    trending: false,
    description: "Exercise bands set",
  },
  {
    id: "s11",
    name: "Nike Trail Shoes",
    price: 130,
    category: "Sports",
    rating: 4.7,
    image: "https://picsum.photos/200/200?random=59",
    inStock: true,
    stock: 85,
    trending: false,
    description: "Off-road running shoes",
  },
  {
    id: "s12",
    name: "Protein Powder 5lb",
    price: 69,
    category: "Sports",
    rating: 4.5,
    image: "https://picsum.photos/200/200?random=60",
    inStock: true,
    stock: 160,
    trending: false,
    discount: 20,
    originalPrice: 79,
  },

  // Books (12 products)
  {
    id: "bk1",
    name: "Atomic Habits",
    price: 18,
    category: "Books",
    rating: 4.8,
    image: "https://picsum.photos/200/200?random=61",
    inStock: true,
    stock: 300,
    trending: true,
    description: "Build good habits, break bad ones",
  },
  {
    id: "bk2",
    name: "The Psychology of Money",
    price: 16,
    category: "Books",
    rating: 4.7,
    image: "https://picsum.photos/200/200?random=62",
    inStock: true,
    stock: 250,
    trending: false,
    description: "Timeless lessons on wealth",
  },
  {
    id: "bk3",
    name: "Harry Potter Box Set",
    price: 89,
    category: "Books",
    rating: 4.9,
    image: "https://picsum.photos/200/200?random=63",
    inStock: true,
    stock: 100,
    trending: true,
    discount: 10,
    originalPrice: 99,
  },
  {
    id: "bk4",
    name: "Deep Work",
    price: 15,
    category: "Books",
    rating: 4.6,
    image: "https://picsum.photos/200/200?random=64",
    inStock: true,
    stock: 200,
    trending: false,
    description: "Rules for focused success",
  },
  {
    id: "bk5",
    name: "The Hobbit",
    price: 12,
    category: "Books",
    rating: 4.8,
    image: "https://picsum.photos/200/200?random=65",
    inStock: true,
    stock: 180,
    trending: false,
    description: "Classic fantasy novel",
  },
  {
    id: "bk6",
    name: "Educated by Tara Westover",
    price: 14,
    category: "Books",
    rating: 4.7,
    image: "https://picsum.photos/200/200?random=66",
    inStock: true,
    stock: 150,
    trending: false,
    discount: 5,
    originalPrice: 15,
  },
  {
    id: "bk7",
    name: "Sapiens",
    price: 17,
    category: "Books",
    rating: 4.8,
    image: "https://picsum.photos/200/200?random=67",
    inStock: true,
    stock: 220,
    trending: true,
    description: "A brief history of humankind",
  },
  {
    id: "bk8",
    name: "Chemistry Textbook",
    price: 120,
    category: "Books",
    rating: 4.5,
    image: "https://picsum.photos/200/200?random=68",
    inStock: true,
    stock: 80,
    trending: false,
    description: "College chemistry guide",
  },
  {
    id: "bk9",
    name: "Where the Wild Things Are",
    price: 10,
    category: "Books",
    rating: 4.9,
    image: "https://picsum.photos/200/200?random=69",
    inStock: true,
    stock: 350,
    trending: false,
    description: "Children's classic book",
  },
  {
    id: "bk10",
    name: "Batman: The Killing Joke",
    price: 13,
    category: "Books",
    rating: 4.7,
    image: "https://picsum.photos/200/200?random=70",
    inStock: true,
    stock: 120,
    trending: false,
    description: "Graphic novel classic",
  },
  {
    id: "bk11",
    name: "The Martian",
    price: 11,
    category: "Books",
    rating: 4.8,
    image: "https://picsum.photos/200/200?random=71",
    inStock: true,
    stock: 190,
    trending: false,
    discount: 15,
    originalPrice: 13,
  },
  {
    id: "bk12",
    name: "Becoming by Michelle Obama",
    price: 19,
    category: "Books",
    rating: 4.9,
    image: "https://picsum.photos/200/200?random=72",
    inStock: true,
    stock: 140,
    trending: true,
    description: "Memoir by former First Lady",
  },
];

async function seedData() {
  try {
    console.log("Starting seed process...");

    // Seed categories
    console.log("Seeding categories...");
    for (const category of categories) {
      await setDoc(doc(db, "categories", category.id), category);
    }
    console.log(`Seeded ${categories.length} categories`);

    // Seed products
    console.log("Seeding products...");
    let productCount = 0;
    for (const product of products) {
      const existing = await getDocs(
        query(collection(db, "products"), where("id", "==", product.id)),
      );
      if (existing.empty) {
        await setDoc(doc(db, "products", product.id), product);
        productCount++;
      }
    }
    console.log(
      `Seeded ${productCount} new products (${products.length} total defined)`,
    );

    console.log("✅ Seed completed successfully!");
    process.exit(0);
  } catch (error) {
    console.error("❌ Seed failed:", error);
    process.exit(1);
  }
}

seedData();
